config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"

  get "tasks/new", to: "tasks#new"
  post "tasks", to: "tasks#create"

  get "tasks/:id", to: "tasks#show", as: :task

  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  post "tasks", to: "tasks#edit"

  patch "tasks/:id", to: "tasks#update"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save # We'll see that in a moment.
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    # {}

    # no need for app/views/restaurants/update.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<body>
  <h1>Edit</h1>
  <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>
  <p><%= link_to "Back to list", tasks_path %></p>
</body>

app/views/tasks/index.html.erb
<body>
    <h1>My tasks</h1>
    <% @tasks.each do |task| %>
      <% if task.completed %>
        <p><input type="checkbox" name="complete" value="1" checked><%= link_to task.title, task_path(task) %></p>
      <% else %>
        <p><input type="checkbox" value="1" name="completed:" ><%= link_to task.title, task_path(task) %></p>
      <% end %>
    <% end %>
      <p><%= link_to "+ add new task", tasks_new_path %></p>
</body>

app/views/tasks/new.html.erb
<body>
  <h1>New task</h1>
  <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.submit %>
<% end %>
  <p><%= link_to "Back to list", tasks_path %></p>
</body>

app/views/tasks/show.html.erb
<body>
  <h1><%= @task.title %></h1>
  <h2><%= @task.details %></h2>
  <% if @task.completed %>
    <p><input type="checkbox" value="1" name="completed:" checked > This is completed</p>
  <% else %>
    <p><input type="checkbox" value="1" name="completed:"> This is completed</p>
  <% end %>
  <p><%= link_to "Back to list", tasks_path %></p>
  <p><%= link_to "Edit!", task_edit_path(@task) %></p>
</body>